updates:
  # Monitor Node.js / NPM dependencies for frontend dashboard
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  # Monitor Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
