import requests
import os
from hybrid_crypto import HybridEncryption

# Load Public Key generated by Middleware
PUB_KEY_PATH = os.path.expanduser("~/security-sentinel/keys/sentinel_public.pem")

with open(PUB_KEY_PATH, "rb") as f:
    pub_pem = f.read()

client_sender = HybridEncryption(public_key_pem=pub_pem)
endpoint_url = "http://127.0.0.1:8000/api/v1/telemetry"
context = "sentinel_v1_telemetry"

# 1. Encrypt Valid Telemetry Payload
raw_log = '{"agent_id": "node-01", "event": "port_scan_detected", "severity": "HIGH"}'
encrypted_payload = client_sender.encrypt(raw_log, associated_data=context.encode("utf-8"))

print("[*] Sending Valid Encrypted Payload...")
response = requests.post(
    endpoint_url,
    json={"payload": encrypted_payload, "context": context}
)
print(f"[+] Status Code: {response.status_code}")
print(f"[+] Server Response: {response.json()}\n")

# 2. Simulate Attacker Tampering With Ciphertext
import base64
raw_bytes = bytearray(base64.b64decode(encrypted_payload))
raw_bytes[-1] ^= 0xFF  # Flip bits in ciphertext
tampered_payload = base64.b64encode(raw_bytes).decode("utf-8")

print("[*] Sending Tampered Encrypted Payload...")
tampered_response = requests.post(
    endpoint_url,
    json={"payload": tampered_payload, "context": context}
)
print(f"[+] Status Code: {tampered_response.status_code}")
print(f"[+] Server Response: {tampered_response.json()}")
